import type { IconType } from "react-icons";
import {
  FaFlask,
  FaRobot,
  FaChalkboardTeacher,
  FaMicrochip,
  FaUsers,
  FaGlobeAfrica,
  FaCalendarAlt,
  FaNewspaper,
  FaDownload,
  FaStar,
  FaHeart,
  FaBrain,
  FaMicroscope,
  FaProjectDiagram,
  FaCode,
  FaLaptopCode,
  FaBook,
  FaFutbol,
  FaHandsHelping,
  FaBus,
  FaTrophy,
  FaLightbulb,
  FaShieldAlt,
  FaUserGraduate,
  FaSeedling,
  FaBullseye,
  FaEye,
  FaCertificate,
  FaUniversity,
  FaHandshake,
  FaDna,
  FaSolarPanel,
  FaIndustry,
  FaPalette,
  FaMusic,
  FaTheaterMasks,
  FaRunning,
  FaCheck,
} from "react-icons/fa";

export const iconRegistry: Record<string, IconType> = {
  FaFlask,
  FaRobot,
  FaChalkboardTeacher,
  FaMicrochip,
  FaUsers,
  FaGlobeAfrica,
  FaCalendarAlt,
  FaNewspaper,
  FaDownload,
  FaStar,
  FaHeart,
  FaBrain,
  FaMicroscope,
  FaProjectDiagram,
  FaCode,
  FaLaptopCode,
  FaBook,
  FaFutbol,
  FaHandsHelping,
  FaBus,
  FaTrophy,
  FaLightbulb,
  FaShieldAlt,
  FaUserGraduate,
  FaSeedling,
  FaBullseye,
  FaEye,
  FaCertificate,
  FaUniversity,
  FaHandshake,
  FaDna,
  FaSolarPanel,
  FaIndustry,
  FaPalette,
  FaMusic,
  FaTheaterMasks,
  FaRunning,
  FaCheck,
};

export function getIcon(name: string): IconType {
  return iconRegistry[name] ?? FaStar;
}
